config/routes.rb
Rails.application.routes.draw do
  get 'users/dash_bords'
  #resources :articles,  path: '/users/articles'
  namespace :users do
    resources :articles
  end
  
  devise_for :users 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
   mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: {maximum: 10}
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles,  dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    users_dash_bords_path(id: current_user.id)
  end
  

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    devise_parameter_sanitizer.permit(:index, keys: [:user_id])

  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = current_user.articles.all
    #@user = User.find(current_user.id)
    #@articles = @user.articles

  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = current_user.articles.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = current_user.articles.new(article_params)
    if @article.save
      flash[:notice] = "記事を作成しました。"
    else
      flash[:alert] = "記事の作成に失敗しました。"
    end
    redirect_to users_article_url(@article)
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    if @article.update_attributes(article_params)
      flash[:notice] = "記事を編集しました。"
    else
      flash[:alert] = "記事の編集に失敗しました。"
    end
    redirect_to users_article_url(@article)
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.delete
    flash[:notice] = "記事「#{@article.title}」を削除しました。"
    redirect_to users_articles_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content, :image, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dash_bords
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Priorapp3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/articles/edit.html.erb
<h1 class="text-center">記事の編集</h1>
<div class="container">
  <div class="row">

<div class="col-6 offset-3">
  <%= form_with(model: @article, url: users_article_path, local: true) do |f| %>
    <div class="form-group pb-1">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group pb-1">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>

    <div class="col-12 mx-auto py-3">
    <div class="text-center py-3">
      <%= f.submit "更新", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to t('.back'), :back %>
</div> 
</div> 
</div> 

app/views/users/articles/index.html.erb
<h1 class="text-center">記事一覧</h1>

<div class="col-10 offset-1">
  <div class="text-center py-3">
    <%= link_to "記事新規作成", new_users_article_path, class: "btn btn-primary text-white col-6" %> 
  </div>
  <div class="col-10 offset-1">
    <table class="table text-center align-middle">
      <thead>
        <tr>
          <th><%= "詳細" %></th>
          <th><%= "タイトル" %></th>
          <th><%= "内容" %></th>
          <th><%= "画像" %></th>
          <th><%= "編集・削除" %></th>
        </tr>
      </thead>
      <tbody>
        <% @articles.each do |a| %>
          <tr>
            <td><%= link_to "詳細", users_article_path(a.id), class: "btn btn-primary text-white" %></td>
            <td><%= a.title %></td>
            <td><%= a.content %></td>
            <td><%= image_tag a.image.url if a.image?%></td>
            <td>
              <%= link_to "編集", edit_users_article_path(a.id), class: "btn btn-success text-white" %>
              <%= link_to "削除", users_article_path(a.id), method: :delete, class: "btn btn-danger text-white ml-1" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div> 

app/views/users/articles/new.html.erb
<h1 class="text-center">記事の新規作成</h1>
<div class="container">
  <div class="row">

<div class="col-6 offset-3">
  <%= form_with(model: @article, url: users_articles_path, local: true) do |f| %>
    <div class="form-group pb-1">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group pb-1">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="text-center py-3">
      <%= f.submit "新規作成", class: "btn btn-primary" %>
    </div>
  <% end %>
  <%= link_to t('.back'), :back %>
</div> 
</div> 
</div> 

app/views/users/articles/show.html.erb
<h1 class="text-center">記事詳細</h1>
<div class="container">
  <div class="row">
<div class="col-10">
  <table class="table text-center offset-2">
    <thead>
      <tr>
        <th><%= Article.human_attribute_name(:title)%></th>
        <th><%= Article.human_attribute_name(:content)%></th>
        <th><%= Article.human_attribute_name(:image)%></th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @article.title %></td>
        <td><%= @article.content %></td>
        <td><%= image_tag @article.image.url if @article.image? %></td>
      </tr>
    </tbody>
  </table>
</div>
</div>
  <div class="text-center">
    <%= link_to "編集", edit_users_article_path, class: "btn btn-success text-white " %>
    <%= link_to "削除", users_article_path, method: :delete, class: "btn btn-danger text-white  ml-1" %>
  </div>

  <div class="text-center my-3">
    <%= link_to "一覧に戻る", users_articles_path, class: "btn btn-primary text-white " %>
  </div>
</div> 

app/views/users/dash_bords.html.erb
<h1 class="text-center">Dash Bords</h1>
<% if user_signed_in? %>
<h3 class="text-center"><%= current_user.name %></h3>
  <div class="col-12 py-2 ">
    <%= link_to "記事一覧", users_articles_path, class: "btn btn-lg btn-primary text-white col-4 offset-4" %>
  </div>
  <div class="col-12 py-2">  
    <%= link_to "編集", edit_user_registration_path, class: "btn btn-lg btn-primary text-white col-4 offset-4" %>
    </div>
  <div class="col-12 py-2">
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "btn btn-lg btn-warning col-4 offset-4" %>
  </div>
  </div>
 <% else %>
    <%= link_to "ログイン", new_user_session_path %>
    <%= link_to "新規登録", new_user_registration_path %>
  <% end %>
</div>